apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: capstone
  labels:
    app: capstone
spec:
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - name: capstone
          image: mahmoudteha/capstone
          ports:
            - containerPort: 80
